Repository paratskiy-organization/neighbor_helper, pull requests merged in 2020-12, with the labels that each got.

#35 Location handler
  package-lock.json
  package.json
  src/actions/commonActions.js
  src/actions/locationAction.js
  src/actions/mainActions.js
  src/constants/button.text.js
  src/constants/flow.step.js
  src/database/migrations/20201128235159-add-state-to-user.js
  src/database/models/user.js
  src/features/buttonHandlers/buttonBackHandler.js
  src/features/buttonHandlers/index.js
  src/features/index.js
  src/features/locationHandler.js
  src/features/stateDefaultHandler.js
  src/features/textHandler.js
  src/helpers/setState/index.js
  src/services/location.service.js
  src/services/user.service.js
  src/templates/aboutUsTemplate/aboutUsMessageTemplate.js
  src/templates/aboutUsTemplate/index.js
  src/templates/locationTemplates/addLocationKeyboardTemplate.js
  src/templates/locationTemplates/addLocationMessageTemplate.js
  src/templates/locationTemplates/addLocationNameKeyboardTemplate.js
  src/templates/locationTemplates/addLocationNameMessageTemplate.js
  src/templates/locationTemplates/index.js
  src/templates/locationTemplates/returnMainMenuMessageTemplate.js
Labels: enhancement

#38 Get only other people's notDone assignments fix.
  src/services/assignment.service.js
Labels: invalid

#49 Assignment actions
  src/actions/assignmentActions.js
  src/features/callbackQueryHandler.js
  src/helpers/ServiceResponse/index.js
  src/helpers/telegram/index.js
  src/services/assignment.service.js
  src/templates/assignmentTemplate/assignmentInlineKeyboardTemplate.js
Labels: bug

#47 Add assignment
  src/actions/addAssignmentAction.js
  src/actions/locationAction.js
  src/actions/mainActions.js
  src/constants/button.text.js
  src/constants/enums/assignmentCategory.js
  src/constants/enums/index.js
  src/constants/flow.step.js
  src/features/buttonHandlers/buttonBackHandler.js
  src/features/buttonHandlers/categoryHandler.js
  src/features/index.js
  src/features/pictureHandler.js
  src/features/stateDefaultHandler.js
  src/features/textHandler.js
  src/helpers/locationNamesKeyboard/index.js
  src/helpers/responseMessage/index.js
  src/templates/addAssignmentTemplates/addDescriptionAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/addPictureAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/addRewardAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/addTitleAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/chooseCategoryAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/chooseLocationAssignmentMessageTemplate.js
  src/templates/addAssignmentTemplates/index.js
  src/templates/addAssignmentTemplates/previewAssignnmentKeyboardTemplate.js
  src/templates/addAssignmentTemplates/previewAssignnmentMessageTemplate.js
  src/templates/addAssignmentTemplates/publishAssignnmentMessageTemplate.js
  src/templates/commonTemplates/commonKeyboardTemplate.js
  src/templates/commonTemplates/index.js
  src/templates/commonTemplates/skipCommonKeyboardTemplate.js
  src/templates/locationTemplates/addLocationNameKeyboardTemplate.js
  src/templates/locationTemplates/index.js
  src/templates/mainMenuTemplate/mainMenuKeyboardTemplate.js
Labels: enhancement

#61 Edit assignment.
  src/actions/addAssignmentAction.js
  src/actions/assignmentActions.js
  src/actions/editAssignmentAction.js
  src/actions/locationAction.js
  src/actions/mainActions.js
  src/constants/button.text.js
  src/constants/flow.step.js
  src/features/buttonHandlers/buttonBackHandler.js
  src/features/buttonHandlers/buttonEditAssignmentHandler.js
  src/features/buttonHandlers/buttonPublishAssignmentHandler.js
  src/features/buttonHandlers/categoryHandler.js
  src/features/buttonHandlers/index.js
  src/features/callbackQueryHandler.js
  src/features/index.js
  src/features/pictureHandler.js
  src/features/stateDefaultHandler.js
  src/features/textHandler.js
  src/helpers/commonKeyboards/commonKeyboard.js
  src/helpers/commonKeyboards/index.js
  src/helpers/commonKeyboards/skipCommonKeyboard.js
  src/helpers/commonKeyboards/skipDeleteCommonKeyboard.js
  src/helpers/responseMessage/assignmentMessage.js
  src/helpers/responseMessage/index.js
  src/helpers/state/index.js
  src/helpers/state/setState.js
  src/helpers/state/stateLoad.js
  src/helpers/telegram/index.js
  src/helpers/validationInputCategory/index.js
  src/services/assignment.service.js
  src/services/location.service.js
  src/services/user.service.js
  src/templates/addAssignmentTemplates/index.js
  src/templates/addAssignmentTemplates/previewAssignnmentMessageTemplate.js
  src/templates/addAssignmentTemplates/publishAssignnmentMessageTemplate.js
  src/templates/assignmentTemplate/assignmentInlineKeyboardTemplate.js
  src/templates/commonTemplates/index.js
  src/templates/commonTemplates/previewAssignmentKeyboardTemplate.js
  src/templates/commonTemplates/previewAssignmentMessageTemplate.js
  src/templates/commonTemplates/publishNewAssignmentMessageTemplate.js
  src/templates/commonTemplates/publishUpdateAssignmentMessageTemplate.js
  src/templates/commonTemplates/skipDeleteCommonKeyboardTemplate.js
  src/templates/editAssignmentTemplates/chooseCategoryMessageTemplate.js
  src/templates/editAssignmentTemplates/chooseLocationAssignmentForEditMessageTemplate.js
  src/templates/editAssignmentTemplates/editDescriptionAssignmentMessageTemplate.js
  src/templates/editAssignmentTemplates/editPictureAssignmentMessageTemplate.js
  src/templates/editAssignmentTemplates/editRewardAssignmentMessageTemplate.js
  src/templates/editAssignmentTemplates/editTitleAssignmentMessageTemplate.js
  src/templates/editAssignmentTemplates/index.js
Labels: enhancement

#63 Add location in add and edit assignment
  src/actions/addAssignmentAction.js
  src/actions/assignmentActions.js
  src/actions/commonActions.js
  src/actions/editAssignmentAction.js
  src/actions/locationAction.js
  src/actions/mainActions.js
  src/constants/button.text.js
  src/features/buttonHandlers/buttonBackHandler.js
  src/features/textHandler.js
  src/helpers/locationNamesKeyboard/index.js
  src/helpers/responseMessage/index.js
  src/helpers/state/setState.js
  src/services/assignment.service.js
  src/services/user.service.js
  src/templates/mainMenuTemplate/mainMenuKeyboardTemplate.js
Labels: enhancement

#66 Resolving updateLocation TODO.
  src/actions/locationAction.js
  src/services/location.service.js
Labels: enhancement

#67 Delete spaces.
  src/actions/locationAction.js
Labels: enhancement
